"""add_serv upgrade

Revision ID: 25efc1643961
Revises: 
Create Date: 2022-10-18 21:12:12.910988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25efc1643961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('add_service', sa.String(length=1000), nullable=True),
    sa.Column('add_price', sa.Integer(), nullable=True),
    sa.Column('type_package', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=120), nullable=True),
    sa.Column('add_services', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('date_order', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_date_order'), 'orders', ['date_order'], unique=False)
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=120), nullable=True),
    sa.Column('rus_name', sa.String(length=120), nullable=True),
    sa.Column('type_name', sa.String(length=120), nullable=True),
    sa.Column('base_service', sa.String(length=1000), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_package_name'), 'package', ['package_name'], unique=True)
    op.create_index(op.f('ix_package_rus_name'), 'package', ['rus_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_rus_name'), table_name='package')
    op.drop_index(op.f('ix_package_package_name'), table_name='package')
    op.drop_table('package')
    op.drop_index(op.f('ix_orders_date_order'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('additional_services')
    # ### end Alembic commands ###
