"""-uniquefor rus_name

Revision ID: 59f2e1ca3bbb
Revises: 25efc1643961
Create Date: 2022-10-19 18:12:05.649081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f2e1ca3bbb'
down_revision = '25efc1643961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_package_rus_name', table_name='package')
    op.create_index(op.f('ix_package_rus_name'), 'package', ['rus_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_rus_name'), table_name='package')
    op.create_index('ix_package_rus_name', 'package', ['rus_name'], unique=False)
    # ### end Alembic commands ###
