"""add new table

Revision ID: 65b12cc55c11
Revises: 188c6cd2086c
Create Date: 2022-10-24 20:15:06.609121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b12cc55c11'
down_revision = '188c6cd2086c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_pub', sa.String(length=1000), nullable=True),
    sa.Column('pub_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_storage', sa.String(length=1000), nullable=True),
    sa.Column('res_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transporting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_trp', sa.String(length=1000), nullable=True),
    sa.Column('trp_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transporting')
    op.drop_table('result_storage')
    op.drop_table('publish')
    # ### end Alembic commands ###
