"""aotuincrement orders tablee

Revision ID: c94a6383fa8d
Revises: 59f2e1ca3bbb
Create Date: 2022-10-19 19:33:34.312674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94a6383fa8d'
down_revision = '59f2e1ca3bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('wed_date', sa.DateTime(), nullable=True))
    op.drop_index('ix_orders_date_order', table_name='orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_date_order', 'orders', ['date_order'], unique=False)
    op.drop_column('orders', 'wed_date')
    # ### end Alembic commands ###
